function [D, G] = FiniteObjectiveGradient(m, con , obj, opts)
%FiniteObjectiveGradient Evaluate the gradient of a set of objective
%   functions by finite difference approximation
%
% Usage:
%   1. Original way, 1st set of input args below. Single model with a
%      vector of conditions and matrix of objective functions, where all
%      conditions are derived from the model, and each row of objective
%      functions is derived from the corresponding condition row.
%	2. New way, 2nd set of input args below. Multiple models,
%      conditions, and objective function vectors, plus an options struct
%      generated by BuildFitOpts to create the desired mapping.
%
%   This function is identical to ObjectiveGradient except that the
%   gradient is calculated differently. This is useful for testing that
%   custom-made objective functions have been coded correctly and that
%   integration tolerances have been set appropriately.
%
% Inputs:
%	m [ model struct scalar | nModel x 1 model struct vector ]
%       The KroneckerBio model that will be simulated
% 	con [ nCon x 1 experiment struct vector | nCon x 1 experiment struct vector ]
%       The experimental conditions under which the model will be simulated
%	obj [ nCon x nCon objective struct matrix | nObj x 1 objective struct vector ]
%       The objective structures defining the objective functions to be
%       evaluated.
%	opts [ options struct scalar ]
%       Options struct with just global opts or detailed options from
%       BuildFitOpts.
%
% Outputs:
%   D [ nT x 1 real vector ]
%       The sum of all objective function gradients
%   G [ scalar real ]
%       The objective function value

%% Work-up
% Clean up inputs
if nargin < 4
    opts = [];
end
if nargin < 4 || ~isfield(opts, 'fit')
    % Convert Usage 1 -> Usage 2
    [m, con, obj, opts] = ConvertFitOpts(m, con, obj, opts);
end
verbose = logical(opts.Verbose);

% Store starting parameter sets
T0 = collectAllActiveParameters(m, con, opts.fit.ComponentMap, opts.fit.Tlocal2T);

%% Loop through conditions
nT = length(T0);
D = zeros(nT,1);

% Initial value
if verbose; fprintf('Initial round\n'); end
G = computeObjAll(m, con, obj, opts, 'val');

for iT = 1:nT
    if verbose; fprintf('Step %d of %d\n', iT, nT); end
    
    % Set baseline parameters
    T_i = T0(iT);
    T_up = T0;
    
    % Change current parameter by finite amount
    step_size = 1e-8;
    if opts.Normalized
        norm_factor = T_i;
    else
        norm_factor = 1;
    end
    if opts.ComplexStep
        imag_factor = 1i;
    else
        imag_factor = 1;
    end
    diff = step_size * norm_factor * imag_factor;
    
    % Compute G
    T_up(iT) = T_up(iT) + diff;
    [m, con] = updateAllActiveParameters(m, con, T_up, opts.fit.ComponentMap, opts.fit.T2Tlocal);
    G_up = computeObjAll(m, con, obj, opts, 'val');

    % Compute D
    if opts.ComplexStep
        D(iT) = imag(G_up) ./ step_size;
    else
        D(iT) = (G_up - G) ./ step_size;
    end
end
