function [G, GAll] = ObjectiveValue(m, con, obj, opts)
%ObjectiveValue Evaluate a set of objective functions
%   
% Usage:
%   1. Original way, 1st set of input args below. Single model with a
%      vector of conditions and matrix of objective functions, where all
%      conditions are derived from the model, and each row of objective
%      functions is derived from the corresponding condition row.
%	2. New way, 2nd set of input args below. Multiple models,
%      conditions, and objective function vectors, plus an options struct
%      generated by BuildFitOpts to create the desired mapping.
%
% Inputs:
%	m [ model struct scalar | nModel x 1 model struct vector ]
%       The KroneckerBio model that will be simulated
% 	con [ nCon x 1 experiment struct vector | nCon x 1 experiment struct vector ]
%       The experimental conditions under which the model will be simulated
%	obj [ nCon x nCon objective struct matrix | nObj x 1 objective struct vector ]
%       The objective structures defining the objective functions to be
%       evaluated.
%	opts [ options struct scalar ]
%       Options struct with just global opts or detailed options from
%       BuildFitOpts.
%
% Outputs:
%	G [ real scalar ]
%       The objective function value
%   GAll [ nCon x 1 double vector ]
%       Individual expt's objective function values, after application of
%       weights

%% Work-up
% Clean up inputs
if nargin < 4
    opts = [];
end
if nargin < 4 || ~isfield(opts, 'fit')
    % Convert Usage 1 -> Usage 2
    [m, con, obj, opts] = ConvertFitOpts(m, con, obj, opts);
end

%% Run appropriate objective evaluation
[G, GAll] = computeObjAll(m, con, obj, opts, 'val');
